Atualiza documentação
okfn-brasil/querido-diario-toolbox pull request #45
Opened 2022-08-26 16:43 UTC by trevineju

Buscando se adequar ao padrão de documentação adotado no projeto (#https://github.com/okfn-brasil/querido-diario-comunidade/issues/14), este PR:

- Adiciona CODE_OF_CONDUCT.md e sua tradução em inglês. Eles apontam para os de Comunidade
- Adiciona CONTRIBUTING.md e sua tradução em inglês. Eles apontam para os de Comunidade
- Adiciona FUNDING.yml
- Adiciona SUPPORT.md e sua tradução em inglês
- Atualiza e move LICENSE.md da raiz para /.github
- Versão do README.md em inglês: Renomeia e move para /.github

2023-02-10 13:26 UTC, trevineju commented
O básico da padronização dos repositórios foi atendido aqui. Itens de melhoria (que poderiam ser incluídos na revisão ou deixados em issues para incremento) são:
- no contributing.md, discriminar a configuração do ambiente em 3 sistemas operacionais (linux, macOS e windows)
- no contributing.md, mencionar desafios relevantes que o repositório ainda quer/precisa superar, indicando possíveis pontos de contribuição

2023-02-13 16:16 UTC, giuliocc requested changes
Comentários feitos no review do PR okfn-brasil/querido-diario#605 também são válidos aqui

2023-02-13 16:16 UTC, giuliocc commented on .github/CONTRIBUTING.md
> +## Como configurar o ambiente de desenvolvimento
Vale adicionar que esse tutorial só foi testado em linux

2023-02-22 20:37 UTC, trevineju commented on .github/CONTRIBUTING.md
> +## Como configurar o ambiente de desenvolvimento
adicionado

2023-02-22 20:38 UTC, trevineju commented
PR atualizado com as alterações, inclusive vindas de okfn-brasil/querido-diario#605

2023-04-19 15:32 UTC, giuliocc requested changes
No geral tá bem legal! Só adicionei dois commits pra corrigir o caminho do README no `setup.py` (que iria atualizar a documentação no PyPI) e subi a versão do projeto.

Algumas coisas precisam ser alteradas ainda:

2023-08-03 15:37 UTC, ogecece approved these changes
LGTM!

2023-08-03 15:37 UTC, merged